# Bookmarks {#bookmarks .unnumbered .unlisted} 

### Indian Section {.unlisted .unnumbered}


<p class="red"> __Dalies__ </p>  
[The Hindu](https://www.thehindu.com/),1878 Chennai, India  
[Hindustan Times](https://www.hindustantimes.com/), 1924 New Delhi, India  
[The Free Press Journal](https://www.freepressjournal.in/), 1928 Mumbai, India  
[The Indian Express](https://indianexpress.com), 1932 Noida, India  
[The New Indian Express](https://www.newindianexpress.com) 1932, 1999 Chennai, India  
[Deccan Chronicle](https://www.deccanchronicle.com), 1938 Hyderabad, India  
[The Economic Times](https://economictimes.indiatimes.com), 1961 Mumbai, India  
[The Financial Express](https://www.financialexpress.com), 1961 Noida, India  
[Business Standard](https://www.business-standard.com/), 1975 New Delhi, India  
[Asian Age](https://www.asianage.com), 1994 New Delhi, India  
[Mint](https://www.livemint.com), 2007 New Delhi, India

<p class="red"> __Television__ </p>  
[NDTV](https://www.ndtv.com), 1988 New Delhi, India  
[CNN News18](https://www.news18.com), 1995 Noida, India

<p class="red"> __Magazines__ </p>  
[India Today](https://www.indiatoday.in), 1975 Noida, India  
[Frontline](https://frontline.thehindu.com), 1984 Chennai, India  
[Outlook](https://www.outlookindia.com/), 1995 New Delhi, India  

<p class="red"> __Online__ </p>  
[Press Information Bureau](https://pib.gov.in/indexd.aspx), GOI (1919)  
[DNA](https://www.dnaindia.com), 2005-2019  
[One India](https://www.oneindia.com), 2006  
[Firstpost](https://www.firstpost.com), late 2010 in Mumbai, India  
[Brookings India](https://www.brookings.edu/center/brookings-india/), 2013 India  
[Scroll.in](https://scroll.in) 2014, Delaware, USA.  
[The Wire](https://thewire.in/), 2015 New Delhi, India  
[The Quint](https://www.thequint.com), 2015 New Delhi, India  
[The Ken](https://the-ken.com), 2016 Bangalore, India  
[Bloomberg Quint](https://www.bloombergquint.com/),2016 India  
[The Print](https://theprint.in),2017 New Delhi, India  


### International Section {.unlisted .unnumbered}
<text class = red> __Dalies__ </text>  
[The Times](https://www.thetimes.co.uk/), 1788 London, UK.  
[The Guardian](https://www.theguardian.com/uk), 1821 London, UK.  
[The New York Times](https://www.nytimes.com/), 1851 New York City, USA.  
[The Telegraph](https://www.telegraph.co.uk/) or The Daily Telegraph (1855), London, UK.  
[The Washington Post](https://www.washingtonpost.com), 1877 Washington D.C., USA.  
[Los Angeles Times](https://www.latimes.com/), 1881 Los Angeles, USA.  
[Financial Times](https://www.ft.com/), 1888 London, UK.  
[The Wall Street Journal](https://www.wsj.com/), 1889 New York City, USA.  
[The Christian Science Monitor](https://www.csmonitor.com/), 1908 Boston, USA.  
[BBC](https://www.bbc.com/), 1922 London, UK.  
[The Australian Financial Review](https://www.afr.com/), 1950 Sydney, Australia.  
[USA Today](https://www.usatoday.com/), 1982 Virginia, USA.  


<text class = red> __Magazines__ </text>

[The Economist](https://www.economist.com/), 1843 London, UK.   
[The Atlantic](https://www.theatlantic.com/world/), 1857 Washington D.C., USA.  
[The Nation](https://www.thenation.com/), 1865 New York City, USA.  
[Los Angeles Daily News](https://www.dailynews.com/), 1911 Los Angeles, USA.  
[The New Republic](https://newrepublic.com/), 1914 New York City, USA.  
[FORBES](https://www.forbes.com/), 1917 New Jersey, USA.  
[Foreign Affairs](https://www.foreignaffairs.com/), 1922 USA.  
[Time](https://time.com/), 1923 New York City, USA.  
[The New Yorker](https://www.newyorker.com/), 1925 New York City, USA.  
[Fortune](https://fortune.com/), 1929 New York City, USA.  
[The Progressive](https://progressive.org/), 1929 Wisconsin, USA.  
[Businessweek](https://www.bloomberg.com/businessweek), 1929 originated independently, later acquired by Bloomberg, New York City, USA.  
[National Review](https://www.nationalreview.com/), 1955 New York City, USA. 
[The National Interest](https://nationalinterest.org), 1985  Washington D.C., USA.  
[The Weekly Standard](https://www.weeklystandard.com/), 1995 Washington D.C., USA.  
[Slate](https://slate.com/), 1996 New York City, USA.  
[Politico](https://www.politico.com/), 2007 Virginia, USA.  

<text class = red> __Television__ </text>  
[Al-Jzeera](https://www.aljazeera.com/), 1996 Doha, Quatar.  
[National Public Radio](https://www.npr.org/), 1970 NPR USA.  
[CNN (Cable News Network)](https://edition.cnn.com/), 1980 Georgia, USA.  
[NBC News](https://www.nbcnews.com/), 1940 New York City, USA.  
[CBS News](https://www.cbsnews.com/), 1927 New York City, USA.  
[ABC](https://abcnews.go.com/) (American Broadcasting Company) News, 1943 California, USA.  
[Australian Broadcasting Corporation](https://www.abc.net.au/), 1929 Sydney Australia.  
[SBS](https://www.sbs.com.au) (Special Broadcasting Service), 1978 Australia.  


<text class = red> __Online__ </text>  
[The Brookings Institution](https://www.brookings.edu/), 1916 Washington D.C., USA.  
[The Pew Research Center](https://www.pewresearch.org/), 1993 Washington D.C., USA.  
[The Bureau of Investigative Journalism](https://www.thebureauinvestigates.com/), 2010 London, UK.  
[Project Syndicate](https://www.project-syndicate.org), late 2000.  
[Vox Media](https://www.voxmedia.com/a/vm), 2011 New York, USA.  
[The Conversation](https://theconversation.com/au), 2011 Australia.  
[Quartz](https://qz.com/) Media, 2012 New York City, USA.  
[Medium](https://medium.com/), 2012 USA.  
[The Intercept](https://theintercept.com/), 2014 USA.  
[Vox](https://www.vox.com/), 2014 New York, USA.  

<text class = red> __News Agencies__ </text>  
[The Associate Press Agency](https://www.ap.org/en-gb/), 1917 New York City, USA.  
[The Associate Press News](https://apnews.com), 1917 New York City, USA.  
[Reuters Agency](https://www.thomsonreuters.com/en.html), 1851 London, UK.  
[Reuters News](https://www.reuters.com), 1851 London, UK.  
[Bloomberg, L.P.](https://www.bloomberg.com) (Limited partnership), 1981 New York, USA.   

### Economic Cornner {.unlisted .unnumbered}

>Some of the above news sources are as much economics as any serious academic papers. Additionally there are some institutes which conduct their own research and give newsletters to your inbox which could be worth the watch. It also depends upon your area of interest within the broad platter of economics.

<text class = red> __Blogosphere__ </text>  

[Marginal Revolution](https://marginalrevolution.com), 2003 Tyler Cowen and Alex Tabarrok, George Mason University.  
[Five Thirty Eight](https://fivethirtyeight.com/), 2008, Nate Silver, owned by ESPN (ABC Media) since 2012.  
[Greg Mankiw's Blog](https://gregmankiw.blogspot.com/), 2006.  
[Macromusings](https://macromarketmusings.blogspot.com/), 2007 David Beckworth.  
[Mainly Macro](https://mainlymacro.blogspot.com/), 2011 by [Simon Wren Lewis](https://sites.google.com/site/sjqwrenlewis/home), Merton College, University of Oxford.  
[Confessions of a Supply Side Liberal](https://blog.supplysideliberal.com/), 2012 by Miles Kimball, Univeristy of Colorado, Boulder.  
[Conversable Economist](https://conversableeconomist.blogspot.com/), 2011 Timothy Taylor.  
[Naked Capitalism](https://www.nakedcapitalism.com/), 2006 various authors.  
[Econbrowser](http://econbrowser.com/), 2005 by [Hamilton](https://econweb.ucsd.edu/~jhamilto/) and [Chinn](https://www.ssc.wisc.edu/~mchinn/).  
[New Economic Perspectives](https://neweconomicperspectives.org/), 2007.  
[The Library of Economics and Liberty](https://www.econlib.org/), 1993.  
[Undercover Economist](https://timharford.com/),Tim Hardford, early 2000s.  
[EconLife](https://econlife.com/), early 2000s by Elaine Swartz.  
[Intelligent Economist](https://www.intelligenteconomist.com/), Prateek Agarwal.  
[Cafe Hayek](https://cafehayek.com/), 2004.  
[Economonitor](https://www.thestreet.com/economonitor/), 2010 Nouriel Roubini.  
[Ed Dolan's Econ Blog](https://dolanecon.blogspot.com/), 2009 [Ed Dolan](https://www.niskanencenter.org/author/ed-dolan/).  
[Audio Econ](https://audioecon.com), 2012 by [Rebecca L. Moryl](https://www.emmanuel.edu/academics/our-faculty/rebecca-moryl.html).  
[Notes on the Crisis](https://nathantankus.substack.com), Nathan Tankus.  
[International Development Economics Association](https://www.networkideas.org) (IDEAS).  
[Vox Development](https://voxdev.org), 2017.  

#### Research Portals {.unlisted .unnumbered}

[The Melbourne Institute](https://melbourneinstitute.unimelb.edu.au), 1962.  
[World Bank Blogs](https://blogs.worldbank.org).  
[Resources for Economist](https://www.aeaweb.org/rfe/toc.php?show=complete), 2017 by the American Economics Association - curated source of economics blogs, data, institutional outreach and publicity.  
[VOX  CEPR Policy Portal](https://voxeu.org/), 2007.  
[IMF Blogs](https://blogs.imf.org/).  
[Peterson Institute of International Economics](https://www.piie.com), PIIE, 1981 Washington D.C., USA.  
[Liberty Street Economics](https://libertystreeteconomics.newyorkfed.org/), New York Fed.  
[Macroblog](https://www.frbatlanta.org/blogs/macroblog.aspx), Atlanta Fed.  
[CEPR](https://cepr.net/),1999 Washington DC.  
[IMF Finance & Development](https://www.imf.org/external/pubs/ft/fandd/index.htm), early 1990s with online issue since 1993, Vol 33 available.  
[International Growth Center](https://www.theigc.org),2008.  
[Institute for New Economic Thinking](https://www.ineteconomics.org/), 2009.  
[The Washington Center for Equitable Growth](https://equitablegrowth.org/), 2013.  
[TATA Center for Development](https://tcd.uchicago.edu), University of Chicago, Delhi, India.  

#### Indian Economy {.unlisted .unnumbered}

[Economic and Political Weekly](https://www.epw.in/), 1949. 
[Ideas of India](https://www.ideasforindia.in), 2012.  
[Institue of Human Development](https://www.ihdindia.org).  


#### Institutions {.unlisted .unnumbered}

[American Economic Association](https://www.aeaweb.org), 1885.  
[The National Bureau of Economic Research](https://www.nber.org), 1920.  
[Bank of International Settlements](https://www.bis.org), 1930.  
[World Bank](https://www.worldbank.org), 1944.  
[IMF](https://www.imf.org/external/index.htm), 1945.  
[CEPR](http://www.cepr.org/) 1983.  
[Levy Economics Institute](http://www.levyinstitute.org), Bard College 1986.  
[World Economic Association](https://www.worldeconomicsassociation.org), 2011.  

#### Agricultural, Environmental and Resource Economics {.unlisted .unnumbered}

[American Agricultural Economics Association](https://www.aaea.org), 1970s, exact date unknown.  
[Choices Magazine](https://www.choicesmagazine.org), 1999.  
[Association of Environmental and Resource Economics](https://www.aere.org/about-aere), 1979.  
[Public Policy Institue of California](https://www.ppic.org), 1994.  

### Reading {.unlisted .unnumbered}

[Poets.org](https://poets.org/) (American Academy of Poets)   
[Farnam Street](https://fs.blog)  
[Naruto Shippuden](https://naruto-shipuden.com)  
[Manganelo](https://manganelo.com/chapter/read_naruto_manga_online_free3/chapter_246)  
[Crunchyroll](https://www.crunchyroll.com/naruto-shippuden)    

### Watching {.unlisted .unnumbered}

[SBS on Demand, 2016](https://www.sbs.com.au/ondemand/)
