# Mathematical Methods for Economics I {.unnumbered .unlisted}



## Course Synopsis {.unnumbered .unlisted}

This is the first part of a two-part course on mathematical methods for undergraduate  students in economics. This course follows the preparatory camp which is mandatory for all students admitted into the BA. (Hons) Economics program at the School of Government and Public Policy at OP Jindal Global University. The aim of this course is to introduce the students to basic tools and techniques of mathematics that form the foundation of modern economics. Learning mathematics could be anxiety inducing for students, but we try and overcome this fear of mathematics by using it to understand economic concepts. We believe that this context helps facilitate learning of mathematics itself and align the usage of this language to economics. 
After taking this course, you would be able to appreciate the mathematical structure of concepts in economics and be able to identify the appropriate methods crucial for economic analysis. This course directly follows from the preparatory camp and assumes knowledge of content therein. However, we will start this course following the exposition in our core texts. We begin with a simplistic economic model. The economic variables and their relationship in the model will introduce us to concepts in sets, relations and functions. 

While the simple model helps us present these, we realize that the world of economics is more complicated than a single equation. It comprises of interconnections which require more description and many more equations. We use insights from the study of a system of equations to understand a complex model which such interconnections. 

But the world is not always linear. So even with many such equations, we fail to understand the world of economics. This brings us to the exploring non-linear equations and the world of calculus. We realize that our economic model is growing in mathematical complexity and we can understand such models by applying simple rules of calculus. We learn calculus by understanding the economics in these models and relying on the economic intuition in turn to learn calculus.

We conclude this course by understanding optimal choices by agents in economics and exploring its mathematical structure.In reality, such choices are often under constraints but we leave that discussion to a follow-up course. 

## Course Goals (Learning Outcomes) {.unnumbered .unlisted}

Participants who successfully complete the course are expected to:

- Break down an economic model into its components i.e variables, parameters and relation. They should be able to do this for all courses in economics with a mathematical structure.

- Understand the concept of a solution to economic models and be able to draw economic insights from the solution. 
- Concisely write a system of linear equations in matrix notation and identify the types of matrices involved.
- Solve a system of matrices through the shortest possible solution and understand the equivalence of matrix solutions with solution through substitution.
- Understand the intuition of rates of change and be able to explain comparative statics of a model.
- Apply total derivatives to isolate moving parts of an economic system.
- Solve an unconstrained optimization and be able to make inference from the solution.

We will use examples from micro and macro economics in the hope that it would facilitate you to think about the mathematics underlying other courses. At the end of this course, you should be able to get rid of your anxiety with mathematics and hopefully employ it to simplify the economics in the rest of the program.

## Mathematics using Computers {.unnumbered .unlisted}

Some of the topics could be solved using rudimentary programming using common programming languages as well as software. The course website would have more information on study material and sessions for programming. The intention of introducing this in the first semester is to again get you started with active learning and to break the monotony of online classes. 

## Course Materials {.unnumbered .unlisted}

- Core Text: Fundamental Methods of Mathematical Economics, Alpha C. Chiang and Kevin Wainright [ACC], 4th Edition, McGraw Hill Education. 
- Core Text - [Mathematics of Economics and Business](https://www.taylorfrancis.com/books/9780203401385), Frank Werner, Yuri N. Sotskov, 1st Edition, Routledge 2006. This book is freely available.

- Additional Text: Mathematics for Economic and Business by R.S Bharadwaj, (2006) Excel Books. 

- Blogs and Popular Resources: There are plenty of Blogs/Popular writings which will help you understand and contribute to the in-class discussions. To simplify matters further, the American Economic Association has complied a [list of resources available online](https://www.aeaweb.org/rfe/) and updates this list frequently.



## Course Outline and Lecture Notes {.unnumbered .unlisted}

__Important__:This syllabus is intended to give the student guidance in what may be covered during the semester and will be followed as closely as possible. However, the instructor reserves the right to modify, supplement and make changes as the course needs arise.

### Topic 1: Introduction to Mathematical Economics {.unnumbered .unlisted}


- Course expectations
    - Grading scheme, 
    - Division of instructor hours,
    - Other book-keeping.

- The Nature of Mathematical Economics, Chapter 1, ACC

__Additional Readings__
 
<h3> Topic 2: Mathematical Models for Economics </h3>    
<ul>  
<li> Economic Models, Chapter 2, ACC</li>
<li> Introduction to Economic modeling, 2.1 </li>
<li> Introduction to Sets, 2.2 </li>
<li> Operations on sets,  2.3 </li>
<li> Relations and Functions, 2.4 </li>
<li> Generalizing Functions, 2.5, 2.6, 2.7</li>
</ul>
<!--
<p> Additional Readings </p>   
<ul>
<li></li>
</ul>
-->



<h3> Topic 3: Equilibrium and its components </h3>
<ul> 
<li> Equilibrium Analysis in Economics, Chapter 3, ACC</li>
<li> Solutions to Economic Models: Equilibrium</li>
<li> Graphical Representation and Solutions, 3.1</li>
<li> Functions to Equilibrium, 3.2 </li>
<li> Non-linear functions and Equilibrium, 3.3, 3.4</li>
<li> Partial vs. General Equilibrium Analysis </li>
</ul>
<p> Additional Readings </p>   
<ul>
<li></li>
</ul>



    
<h3> Topic 4: Linear Algebra </h3>
<ul> 
<li> Linear Models and Matrix Algebra, Chapter 4, ACC</li>
<li> Matrices, vectors and their operations, 4.1-4.4 </li>
<li> Special Matrices, 4.5-4.7</li>
<ul>
<li>Identity, Null, Transpose, Probability Matrices</li></ul>
<li> Linear Models and Matrix Algebra (continued), Chapter 5, ACC</li>
<li> Solution to Linear Systems and Singularity of Matrices, 5.1</li>
<li> Determinants and Non Singularity, 5.2, 5.3 </li>
<li> Inverse, Cramers rule and solution to linear system, 5.4, 5.5 </li>
<li> Applications in Micro and Macroeconomic systems, 5.6-5.7</li>
</ul>
<!--
<p> Additional Readings </p>   
<ul>
<li></li>
</ul>
-->

<h3> Topic 5: Introduction to a Non-Linear World</h3>
<ul>
<li> Exponential and Logarathmic Function, Chapter 10, ACC</li>
<li> Nature and Properties of Exponential Function: 10.1,10.2</li>
<li> Logarithmic Functions: 10.3, 10.4 </li>
<li> Inequalities and Absolute Value: 6.5 </li>
<li> Comparative Statics and the concept of Derivative, Chapter 6, ACC </li>
<li> Comparative Statics and Slope Gradient : 6.1-6.3</li>
<li> Limits: 6.4, 6.6 (*tentative)</li>
<li> Continuity and Differentiability: 6.7 (*tentative)</li>
</ul>

  
<h3> Topic 6: Comparative Statics and Derivatives</h3>
<ul> 
<li> Rules of Differentiation and their Use in Comparative Statics, Chapter 7, ACC</li>
<li> Derivatives for Single Variable: 7.1 </li>
<li> Derivatives of Exponentials and Logarathims: 10.5,10.7</li>
<li> Generalizing comparative statics </li>
<li> Two variables and chain rule : 7.2,7.3</li>
<li> Partial differentiation and applications: 7.4-7.6</li>
</ul>



<h3> Topic 7: Analyzing Multivariate functions of Economic Variables</h3>
<ul>
<li> Comparative Static Analysis of General-Function Models, Chapter 8</li>
<li> Total Differentiation: 8.1 - 8.4</li>    
<li> Implicit Function Theorem: 8.5</li>
<li> Applications: 8.6 </li>
<li> Limitations of Comparative Statics: 8.7 </li>
</ul>
<p> Additional Resources: </p>
<ul>
<li> Integration by Parts by <a href="https://www.intmath.com/methods-integration/7-integration-by-parts.php", target="_blank">Interactive Mathematics</a></li>
</ul>


<h3> Topic 8: Univariate Optimization </h3>
<ul>
<li> Optimization: A Special Variety of Equilibrium Analysis, Chapter 9, ACC</li>
<li> Extreme Values: 9.1</li>
<li> First Derivative Test: 9.2</li>
<li> Second and Higher Order Derivative: 9.3, 9.4</li>
<li> Taylor series approximation: 9.5 </li>
</ul>



<h3> Topic 9: Multivariate Optimization </h3>
<ul> 
<li> The Case of More than One Choice Variable, Chapter 11, ACC</li>
<li> Adjustments to Optimization condition: 11.1</li>
<li> Extreme values to Bivariate functions: 11.2,11.3 and 11.4</li>
<li> Optimization, convexity, comparative statics: 11.5,11.7</li>
<li> Applications 11.6</li>
</ul>


<!--
<h3> Topic 9: Constraint Optimization</h3>
<ul>
<li> Constraints, stationary values and second order condition (12.1-12.3)</li>    
<li> Quasi-convesity (12.4)</li>
<li> Consumers utility maximization problem (12.5) </li>
<li> Homogenous functions and production (12.6)</li>
</ul>

-->
