---
title: "Nikhil Damodaran"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: /Users/nikhildamodaran/Dropbox/Journal_Articles/References.bib
biblio-style: apalike
link-citations: yes

---

# {#Home .unnumbered}

Assistant Professor <br>
[School of Government and Public Policy](http://jsgp.edu.in/) <br>
[OP Jindal Global University](https://jgu.edu.in/)

Cabin 6, T4, Academic Block <br>
OP Jindal Global University, Sonipat, Haryana <br>
Email: [ndamodaran@jgu.edu.in](mailto:ndamodaran@jgu.edu.in)


Welcome to my webpage!
Here is a [short introduction](bio.html) and here's my latest blog post. 


### Research {.unlisted .unnumbered}

My research focuses on transmission of economic policy across open economies.

I examine transmission in a variety of setting. I analyze regional economies which form a part of a fiscal unions in my paper "Fiscal Policy and Transmission: The Case of India's States", which is currently under review. I also look at transmission of fiscal policies for the Eurozone in my paper "Trade Transmission of Fiscal Policies in a Currency Union". I am broadly interested in the effect of policy transmission for these regions especially due to their huge interdependence, which makes policy making a strategic and consequnetial exercise for these regions - in addition to its contributions to supra-regional economic performance.

In similar spirit, I examine transmission of Demonetization shock on the Indian economy in a paper "[Consumer Payment Choice and the Heterogeneous Impact of India's Demonetization](https://www.monash.edu/__data/assets/pdf_file/0005/2252795/07-20-Consumer-payment-choice-and-demonetizationedited-final.pdf)" in which we look at the disaggregate effects of India's demonetization through short payment choices for consumers. This is largely regional transmission of this monetary shock.


### Teaching {.unlisted .unnumbered}

I teach Macroeconomics I and II, International Trade, Mathematical Methods for Economics, Statistics II all of which are compulsary courses for BA.(Hons) Economics at O.P. Jindal Global University.

__Ongoing courses__:

EC 13: [Macroeconomics II](macro.html) -  Fall 2020 

EC 01: [Mathematical Methods for Economics I](mathematical-methods.html), Fall 2020


