---
title: RBI and uncoventional monetary policy for financing state expenditures during the Pandemic
author: Nikhil Damodaran
date: '2020-04-18'
categories:
  - published post
tags:
  - economics
slug: rbi-s-response-to-covid-19-needs-to-be-localized-and-unconventional
DisableComments: no
---

Published as [Indian Express, April 24, 2020](https://indianexpress.com/article/opinion/columns/rbi-coronavirus-covid-19-state-governments-imf-gdp-growth-india-6377682/)  

The [IMF](https://indianexpress.com/article/world/united-states/imf-projects-indias-growth-rate-at-1-9-this-year-forecasts-global-recession-due-to-covid-19-6362458/) has massively downgraded India’s projected GDP growth rate for the current fiscal year to 1.9% , from an already low forecast of 4.2% before the start of the COVID-19 pandemic.^[“Unlike a financial crisis or natural disaster, a pandemic causes a deep shock, and is followed by a strong recovery, but there may be some permanent loss of output.”, said an IMF official who expects a V-shaped recovery. Such statements about the nature of recovery, without a comprehensive examination of the sectoral and regional effects of the lockdown are bound to be wishful thinking and crude guesses. [Express, April 22](https://indianexpress.com/article/business/economy/economy-headed-for-contraction-less-fiscal-space-for-big-stimulus-6373356/).] Its [International Monetary and Financial Committee (IMFC)](https://indianexpress.com/article/coronavirus/covid-19-global-fiscal-measures-liquidity-injections-near-usd-14-trillion-says-imf-6367752/) has urged deployment of all policy tools to defeat the pandemic. For India, this translates to an active monetary policy by the Reserve Bank of India (RBI) which goes hand in hand with an expansionary fiscal policy by both the center and state governments. In my view, if the RBI were to unconventionally intervene in [directly financing state expenditures](https://economictimes.indiatimes.com/news/economy/policy/covid-19-allow-states-to-directly-borrow-from-rbi-says-kerala-fm-thomas-isaac/articleshow/75107034.cms), it could go a long way in empowering localized fiscal responses for the pandemic which would then prevent a massive fall in output.

RBI has been [proactive](https://www.telegraphindia.com/business/coronavirus-pandemic-rbi-plan-to-beat-the-bug/cid/1764698) in using conventional monetary policy measures such as a reduction in repo, reverse repo and bank rate to boost liquidity. It has also communicated its will to do [whatever is necessary](https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=49659) to instill investor confidence and stabilize output. To top it further, the governor came out with a [second series](https://www.livemint.com/industry/banking/rbi-governor-shaktikanta-das-press-conference-live-updates-rate-cut-coronavirus-latest-news-11587096658209.html) of rate cuts and [liquidity injections](https://www.livemint.com/opinion/columns/rbi-announces-another-round-of-measures-more-expected-11587128240377.html) which included Non-Banking Financial Companies (NBFC) to disburse credit. However, RBI could do more. It could opt for unconventional measures such as the ones taken either by the US Federal Reserve (Fed) or the Bank of England (BoE). The former has entered the [municipal bonds market](https://www.ft.com/content/e2d20041-0d86-4dea-8016-d1cfcc01f4c0) which has led to a reduction in the interest rate at which [local municipalities borrow](https://www.wsj.com/articles/a-fed-bailout-is-wrong-for-states-and-cities-11586988167) – decreasing their borrowing cost. BoE, on the other hand, is directly [financing](https://www.ft.com/content/664c575b-0f54-44e5-ab78-2fd30ef213cb) its central government deficit, bypassing the bond markets altogether – it is monetizing its government’s debt. Can RBI implement such unconventional measures to ease financing burden of the state governments, who are at the forefront of a containment battle against the coronavirus? Can monetary policy be localized to effectively deal with the economic fallout of the pandemic?

RBI contributes to state finances by providing them with short term loans called the “[ways and means advances](https://indianexpress.com/article/explained/reserve-bank-of-india-rbi-ways-and-means-advances-wma-repo-rate-coronavirus-covid-19-6367396/)” (WMA). Since these advances are for a [short tenure](https://www.business-standard.com/about/what-is-ways-and-means-advances), they do not account for a significant fraction of the state governments’ finances. These advances are meant to facilitate operational expenses of the states and provide short term liquidity. Recently, RBI has increased limits on WMAs in anticipation of the fiscal needs by the governments, twice. However, from an earlier sanctioned limit of Rs. 750 billion, the states only availed Rs. 26.6 bn. during 2018-19. This begs the question: why do these WMAs remain under-utilized? This could be attributed to the short-term nature of these WMAs which prevent effective utilization by the states for their mostly medium-to-long-term requirements. Further, a sharp decline in economic activity because of the lockdown implies that revenues are not enough to make use of and repay these advances on time. 

State governments have been increasingly financing their expenditures through market borrowings and RBI’s efforts to ease limits on WMAs does not seem to affect their behavior. A part of the reason is the significant room of tenure on these market loans. Most of these “State Development Loans” (SDL) are floated for a period of 10 years, pay a higher interest rate than bonds from the center and qualify for investments under statutory requirements by the RBI.

Could all states endlessly rely on such market borrowings? This depends on the market’s assessment of a state’s fiscal position. If a state maintains a high fiscal deficit to GDP ratio, it would be considered a risky borrower and hence would face a higher interest rate in the market. For instance, [Odisha](https://timesofindia.indiatimes.com/city/bhubaneswar/cag-pulls-up-odisha-govt-for-mindless-borrowing/articleshow/72283953.cms) pays a higher interest rate to obtain loans from the market than [Maharashtra](https://economictimes.indiatimes.com/markets/bonds/govt-sticks-to-fy20-borrowing-plan-to-raise-rs-2-68-lakh-crore-in-h2/articleshow/71377314.cms?from=mdr), even under normal circumstances. This implies that states lower down the economic ladder would face greater hardships in sustaining their finances.  Further, with the onset of the Goods and Service Tax (GST), the capacity of state governments to generate revenues on their own has become limited. This has led to an even larger reliance on market borrowings.^[RBI [Annual Report](https://www.rbi.org.in/scripts/AnnualReportPublications.aspx?Id=1262): Public Debt Management states “The share of market borrowing in financing GFD has increased from 65.8 per cent in 2016-17 to 90.6 per cent in 2018-19 (BE), mainly due to the drying up of other sources of financing.”] The existing economic differences between states might permeate into lasting divergence in development outcomes, if market incentives are allowed to dictate their cost of borrowing, in the middle of this pandemic!

RBI must venture into unconventional monetary policy and design alternatives to significantly ease the pressures of financing on the state governments. This can become an equalizer especially given that the state governments were standing on significantly divergent economic performances, when the pandemic hit their economies. There are a few options which, in my view, are intelligible economics.

First, if RBI could temporarily increase the duration of credit disbursed through WMAs, it could substitute a sizable portion of the market borrowings and gear state governments for a credible fight against the pandemic. The uptake of WMAs with its recently increased limits might be inadequate especially for states.

Second, RBI could enter the secondary market for state government bonds and assume an indirect role in purchasing bonds as part of domestic investment by its Banking Department. The resultant increased demand for these state government bonds would lead to a reduction in their interest rates. This reduction would then translate into lower cost of borrowings for the state governments and more sustainable debt position. This is akin to the role played by the US Fed in the municipal bonds market, or their Quantitative Easing programs following the 2008 recession. 

Third, RBI could directly purchase government bonds from the state governments without entering the government bond market. Such a proposal is similar to the recent monetization of government debt by BoE. This would go a long way in reducing the cost of borrowing for states and facilitate a feasible exit strategy when the pandemic is over. Typically, economists do not advocate such direct monetization due to inflationary concerns. But inflation rate remains below the target 4% and continues to trend downwards, indicating the urgent need to infuse demand without worrying about any perverse effects of monetization ^[“According to him, early developments suggest that inflation is on a declining trajectory, having fallen by 170 basis points from its January 2020 peak. In the period ahead, inflation could recede even further, barring supply disruption shocks and may even settle well below the target of 4 per cent by the second half of 2020-21.”, on a press conference the RBI governor claims he does not need to worry about inflation while making these policy decisions now, [April 18](https://indianexpress.com/article/business/economy/shaktikanta-das-sees-v-shaped-recovery-growth-rate-at-7-4-in-fy22-6367483/). This [special report](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiL8bCHpv3oAhVEwzgGHYoaDzgQFjAAegQIAhAB&url=https%3A%2F%2Fwww.economist.com%2Fspecial-report%2F2019%2F10%2F10%2Finflation-is-losing-its-meaning-as-an-economic-indicator&usg=AOvVaw2xeNFEfY1joLDbRvVPGj-E) by the economist argues that governments could borrow a lot and since inflation is low and prices don’t seem to trend upwards globally, they could even monetize their debts indefinitely.]. Operationalizing this would imply amendments to the FRBM Act, which under these circumstances could be done under executive orders, much like other things in the economy. Even the former finance minister Yashwant Sinha who introduced the FRBM Bill concedes to this logic.^[A plan for the aftermath: [Yashwant Sinha](https://indianexpress.com/article/opinion/columns/coronavirus-lockdown-economy-rbi-yashwant-sinha-6356951/) appeared on March 11 in the Indian express. [Even states in US](https://nyti.ms/2Ku511E) also have budget limits which prevent them from spending. The alternatives are that they reduce operating expenses which imply layoffs points out [Claudia Sahm](https://nyti.ms/2Ku511E). ]  
